# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: containers.k8s-registry.{{ .Values.ccrn.apiGroup }}
    annotations:
        ccrn/v1.urn-template: "urn:ccrn:<ccrn>/<instance>/<kv>/<path>"
        ccrn/v1.url-template: "https://<ccrn>/<instance>/<kv>/<path>"
spec:
    group: secret.vault.{{ .Values.ccrn.apiGroup }}
    names:
        kind: secret
        listKind: secretList
        plural: containers
        singular: container
    scope: Namespaced
    versions:
        -   name: v1
            served: true
            storage: true
            schema:
                openAPIV3Schema:
                    type: object
                    required: [ "ccrn", "instance", "kv", "path" ]
                    properties:
                        # Required
                        ccrn:
                            type: string
                            enum: [ "secret.vault.{{ .Values.ccrn.apiGroup }}/v1" ]
                        instance:
                            type: string
                            description: "Vault Instance"
                            enum: [ "global", "qa" ]
                        kv:
                            type: string
                            description: "The secret engine where the secret is stored"
                            pattern: "^([a-z0-9]([a-z0-9-]*[a-z0-9])?|\\*)$"
                            maxLength: 63
                        path:
                            type: string
                            description: "The secret path"
                            pattern: "^([a-z0-9]([a-z0-9-]*[a-z0-9]\/)?|\\*)$"
                            maxLength: 63

            additionalPrinterColumns:
                -   name: CCRN
                    type: string
                    jsonPath: .ccrn
                -   name: Cluster
                    type: string
                    jsonPath: .cluster
                -   name: Namespace
                    type: string
                    jsonPath: .namespace
                -   name: Name
                    type: string
                    jsonPath: .name
                -   name: Pod
                    type: string
                    jsonPath: .pod
                -   name: Age
                    type: date
                    jsonPath: .metadata.creationTimestamp
