# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: containers.k8s-registry.{{ .Values.ccrn.apiGroup }}
    annotations:
        ccrn/v1.urn-template: "urn:ccrn:<ccrn>/<cluster>/<namespace>/<pod>/<name>"
        ccrn/v1.url-template: "https://<ccrn>/<cluster>/<namespace>/<pod>/<name>"
spec:
    group: k8s-registry.{{ .Values.ccrn.apiGroup }}
    names:
        kind: container
        listKind: containerList
        plural: containers
        singular: container
    scope: Namespaced
    versions:
        -   name: v1
            served: true
            storage: true
            schema:
                openAPIV3Schema:
                    type: object
                    required: [ "ccrn", "cluster", "namespace", "pod", "name" ]
                    properties:
                        # Required
                        ccrn:
                            type: string
                            enum: [ "container.k8s-registry.{{ .Values.ccrn.apiGroup }}/v1" ]
                        cluster:
                            type: string
                            description: "The cluster the container is running in"
                            enum: [ "eu-de-1", "eu-de-2", "eu-de-3", "*" ]
                        namespace:
                            type: string
                            description: "The Namespace the container is running in"
                            pattern: "^([a-z0-9]([a-z0-9-]*[a-z0-9])?|\\*)$"
                            maxLength: 63
                        pod:
                            type: string
                            description: "The name of the Pod the Container is running in"
                            pattern: "^([a-z0-9]([-a-z0-9]*[a-z0-9])?|\\*)$"
                            maxLength: 253
                        name:
                            type: string
                            description: "The name of the Container"
                            pattern: "^([a-z0-9]([-a-z0-9]*[a-z0-9])?|\\*)$"
                            maxLength: 253

                        # Optional
                        id:
                            type: string
                            description: "This is the containerID of the container describing the concrete ephemeral container"
                            pattern: "^([a-zA-Z0-9:.-_]+|\\*)$"
                        labels:
                            type: object
                            additionalProperties:
                                type: string
                            description: "Labels for selecting groups of containers"
                        ownerKind:
                            type: string
                            description: "Kind of the owner resource (deployment, job, daemonset, statefulset)"
                            enum: [ "Deployment", "Job", "DaemonSet", "StatefulSet", "*" ]
                        ownerName:
                            type: string
                            description: "Name of the owner resource"
                            pattern: "^([a-z0-9]([-a-z0-9]*[a-z0-9])?|\\*)$"

            additionalPrinterColumns:
                -   name: CCRN
                    type: string
                    jsonPath: .ccrn
                -   name: Cluster
                    type: string
                    jsonPath: .cluster
                -   name: Namespace
                    type: string
                    jsonPath: .namespace
                -   name: Name
                    type: string
                    jsonPath: .name
                -   name: Pod
                    type: string
                    jsonPath: .pod
                -   name: Age
                    type: date
                    jsonPath: .metadata.creationTimestamp
