apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: deployment.k8s-registry.{{ .Values.ccrn.apiGroup }}
    annotations:
        ccrn/v1.urn-template: "urn:ccrn:<ccrn>/<cluster>/<namespace>/<name>"
        ccrn/v1.url-template: "https://<ccrn>/<cluster>/<namespace>/<name>"
spec:
    group: k8s-registry.{{ .Values.ccrn.apiGroup }}
    names:
        kind: deployment
        listKind: deploymentList
        plural: deployments
        singular: deployment
    scope: Namespaced
    versions:
        -   name: v1
            served: true
            storage: true
            schema:
                openAPIV3Schema:
                    type: object
                    required: [ "ccrn", "cluster", "namespace", "name" ]
                    properties:
                        # Required
                        ccrn:
                            type: string
                            enum: [ "deployment.k8s-registry.{{ .Values.ccrn.apiGroup }}/v1" ]
                        cluster:
                            type: string
                            description: "The cluster the deployment is running in"
                            enum: [ "eu-de-1", "eu-de-2", "eu-de-3", "*" ]
                        namespace:
                            type: string
                            description: "The Namespace the deployment belongs to"
                            pattern: "^([a-z0-9]([a-z0-9-]*[a-z0-9])?|\\*)$"
                            maxLength: 63
                        name:
                            type: string
                            description: "The name of the Deployment"
                            pattern: "^([a-z0-9]([-a-z0-9]*[a-z0-9])?|\\*)$"
                            maxLength: 253

                        # Optional
                        labels:
                            type: object
                            additionalProperties:
                                type: string
                            description: "Labels for selecting groups of deployments"

            additionalPrinterColumns:
                -   name: CCRN
                    type: string
                    jsonPath: .ccrn
                -   name: Cluster
                    type: string
                    jsonPath: .cluster
                -   name: Namespace
                    type: string
                    jsonPath: .namespace
                -   name: Name
                    type: string
                    jsonPath: .name
                -   name: Age
                    type: date
                    jsonPath: .metadata.creationTimestamp
