# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: ccrn.validate.{{ .Values.ccrn.apiGroup }}
spec:
    group: validate.{{ .Values.ccrn.apiGroup }}
  names:
    kind: CCRN
    listKind: CCRNList
    plural: ccrns
    singular: ccrn
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-validations:
                - rule: "has(self.ccrn) || has(self.urn)"
                  message: "At least one of 'ccrn' or 'urn' must be specified"
              properties:
                ccrn:
                  type: string
                  pattern: "^ccrn: .+"
                urn:
                  type: string
                  pattern: "^urn:ccrn:.+"
